### ISSUE TITLE
Can't save blank fields

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#242] opened 2015-01-26 19:21 UTC
For some reason I can't save blank fields on a site I'm working on. The field gets the value of "275".

I'm going to do more debugging, but I wanted to put this here mostly as a reminder to myself!

**Comment by jchristopher** [comment] 2015-01-26 19:43
I ran into something similar earlier today but it didn't carry enough weight for me to submit an Issue about it because it was kind of an edge case.

I had a Relationship field with 5 values in it. Those 5 related objects were since deleted. Went back to the edit screen, saw the Relationship field was empty, I clicked Update, but when I `print_r()`'d the original values were still there.

I haven't taken the proper time to recreate the issue (slammed today) but glad you made your note because now I can use it as my note as well haha

**Comment by mgibbs189** [comment] 2015-02-09 18:19
@jchristopher @chrisvanpatten from what you can tell, is the issue specific to relationship fields?

**Comment by jchristopher** [comment] 2015-02-09 18:22
Yes I believe so, still haven't had a chance to nail down a reproduce-able test case but the gist was:

* Relationship field saved chosen values
* Chosen values were deleted
* Re-loading edit screen in WP admin with Relationship field did not have chosen values, but viewing the front end did
* Going back to WP admin and clicking Update (idea being to 'flush out' the deleted data) and then reloading the front end brought up those same, deleted values
* Had to add new values to the Relationship field, save, and then clear out to really wipe it out (I think — it's been a little while, sorry!)

**Comment by chrisvanpatten** [comment] 2015-02-09 19:48
No, I had this problem with a standard text field that wasn't inside a loop field.

I'll pull up the VM with the problem and see what I can find out

**Comment by mgibbs189** [comment] 2015-02-10 01:27
OK, thanks guys.

**Comment by chrisvanpatten** [comment] 2015-02-10 12:33
Just a heads up, here's a video of I'm seeing: https://vid.me/fwwt

Working on getting into the logs next.

**Comment by chrisvanpatten** [comment] 2015-02-10 12:39
Okay, now it's getting interesting.

Here are my fields:

![edit_options_ _bryce_pinkham_ _wordpress](https://cloud.githubusercontent.com/assets/1231306/6127316/67ae2edc-b0f7-11e4-949a-10deeea1655f.png)

And here's what I have in custom fields:

![edit_options_ _bryce_pinkham_ _wordpress](https://cloud.githubusercontent.com/assets/1231306/6127290/3e0ff9a2-b0f7-11e4-8ab2-93ab4d5c2d9a.png)

In the DOM on that screen, the Facebook field and the Homepage Image field share the same `name`:

![developer_tools_-_http___dev_brycepinkham_com_wp_wp-admin_post_php_post_277_action_edit](https://cloud.githubusercontent.com/assets/1231306/6127344/ce3cb1c8-b0f7-11e4-8410-2f4d5f373a55.png)

I exported the JSON for both those field groups, and they have the same ID set there as well.

**Comment by chrisvanpatten** [comment] 2015-02-10 12:44
Also, FWIW, I am using my [CFS Options Pages](https://github.com/vanpattenmedia/cfs-options-pages) plugin in this instance, but I don't think that caused the problem, since it's just a standard post type.

**Comment by mgibbs189** [comment] 2015-02-10 13:33
Thanks the the detailed report, @chrisvanpatten. At this point, I have no idea why the ID would get duplicated :\

**Comment by chrisvanpatten** [comment] 2015-02-10 14:54
I'll keep playing around with it and see what I can find.

My current operating theory is that it has something to do with the way I move content between different environments. For example, maybe I created a field group in staging, then another field group in dev, then exported from staging and imported to dev, which caused the duplicate field IDs.

Or something like that.

I'll continue to poke around, and see if I can replicate it from scratch.

**Comment by mgibbs189** [comment] 2015-05-08 00:04
Closing for now...

**Closed by mgibbs189** 2015-05-08 00:04 UTC

**Comment by chrisvanpatten** [comment] 2015-05-08 11:31
Yeah it's totally an issue with IDs not matching up somehow. It's pretty much exclusive to my environment/workflow as far as I can tell.
