### ISSUE TITLE
Custom datepicker should not be applied to other plugins fields

### ISSUE THREAD

**Issue by scrobbleme** [mgibbs189/custom-field-suite#378] opened 2016-12-16 13:02 UTC
Hello,

The custom datepicker is also applied to fields in meta boxes from other plugins, for instance WooCommerce Germanized. This sometimes results in wrong date formats.

The datepicker should only be applied on fields from CFS. 
Even better: the already included datepicker should be used.

Thanks,

Adrian

**Comment by mgibbs189** [comment] 2016-12-19 20:29
@scrobbleme can you confirm this is due to CFS?

Our date picker targets input fields within a `.cfs_date` container element.

**Comment by chrisvanpatten** [comment] 2016-12-19 21:05
I downloaded and installed the free version of WooCommerce Germanized but was unable to replicate any issues.

@scrobbleme Are you using the Pro version? Can you send some screenshots showing the issue?

**Comment by chrisvanpatten** [comment] 2017-01-24 15:06
@scrobbleme I'm going to close this issue, but if you can come back and provide some more documentation/steps to reproduce the issue feel free to create a new issue (or comment again on this one).

**Closed by chrisvanpatten** 2017-01-24 15:06 UTC
